# Generated by Django 3.0.6 on 2020-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=48)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(blank=True, to='main.Producto')),
            ],
            options={
                'verbose_name': 'Tag de Productos',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
