# Generated by Django 3.0.6 on 2020-06-07 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion1', models.CharField(max_length=60, verbose_name='Dirección Linea 1')),
                ('direccion2', models.CharField(blank=True, max_length=60, verbose_name='Dirección Linea 1')),
                ('codigo_postal', models.CharField(max_length=12, verbose_name='ZIP / Código Postal')),
                ('ciudad', models.CharField(max_length=60)),
                ('pais', models.CharField(choices=[('mx', 'Estados Unidos Mexicanos')], max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ('Direcciones',),
            },
        ),
    ]
