# Generated by Django 3.0.6 on 2020-06-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Dirección Linea 2'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(choices=[('mx', 'Mexico')], max_length=3),
        ),
    ]
