# Generated by Django 3.0.6 on 2020-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='producto-thumbnails'),
        ),
    ]
