# Generated by Django 3.0.6 on 2020-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200607_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(choices=[('Mexico', 'Mexico')], max_length=12),
        ),
    ]
