# Generated by Django 3.0.6 on 2020-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200607_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(choices=[('mx', 'Mexico')], max_length=3),
        ),
    ]
