# Generated by Django 3.0.6 on 2020-06-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200607_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(choices=[('mx', 'Mexico'), ('eu', 'EUA')], max_length=3),
        ),
    ]
